apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data
  namespace: mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data      #nfs共享目录
    server: 192.168.186.129     #nfs服务器地址
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs