kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data
  namespace: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs